[WIP] Fix for PORTAL_STORAGE_PGHOST in helm deployments
Haufe-Lexware/wicked.portal-env pull request #8
Opened 2019-01-01 21:41 UTC by stackedsax

This is just a WIP PR to see if I'm on the right track here.

This is in reference to Issue Haufe-Lexware/wicked.haufe.io#139.  Helm deployments are failing because the `PORTAL_STORAGE_PGHOST` is using the default value of `wicked-database` instead of the k8s hostname.

I noticed that `updateStep12_v1_0_0c` and `updateStep10_v1_0_0a` both had to explicitly update the k8s environment, so I simply followed that process with `updateStep14_v1_0_0e`.

I haven't figured out exactly how I'm going to test that the right values are getting set.  I'd prefer not to go through the whole process of pushing a new image to a personal docker repo to test this out with helm, but I also can't quite envision how to spin up the docker image by itself and pass it all the variables that get set when I run helm.  I thought it might be as simple as setting `envName=k8s` when I spin up the container, but I tried that and it didn't look like what I was expecting. 

At this point, I'd just like to hear feedback that this PR is on the right track.  Feedback very welcome, especially if it's "stop, you're doing it all wrong".

2019-01-01 21:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/apim-haufe-io/wicked.portal-env?pullRequest=8) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/apim-haufe-io/wicked.portal-env?pullRequest=8) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/apim-haufe-io/wicked.portal-env?pullRequest=8) it.</sub>

2019-01-02 08:45 UTC, DonMartin76 commented
Hi, yes, this is absolutely the right track. Locally, we have all been testing with the sample repository which had those adaptions in place. Thanks a bunch for this!

Unfortunately, I am sick after travelling a lot, so I haven't been able to test this yet. There may also be other loose ends regarding the configuration update, but this is definitely one of the more tedious ones.

There may also be something regarding the redis configuration, have you experienced any issues there?

2019-01-02 14:58 UTC, stackedsax commented
Thanks for the feedback, good to know it's the right direction.  And sorry that you're ill!

The redis container came up just fine, so nothing to worry about there yet.  I suppose it remains to be seen whether the application speaks to the various containers correctly, but as far as kubernetes goes it as alright.

2019-01-03 08:27 UTC, DonMartin76 requested changes

2019-01-03 08:27 UTC, DonMartin76 commented on src/config-updater.js
> +                    value: "http://${LOCAL_IP}:5432"
This can't be right, it has to be `PORTAL_STORAGE_PGHOST`. not `PORTAL_ECHO_URL`, and the value should just be `${LOCAL_IP}`. The password should probably default to the `default` environment's setting, and as a fallback to `kong`.

2019-01-03 08:27 UTC, DonMartin76 commented on src/config-updater.js
> +                debug('Adding ' + JSON.stringify(source.PORTAL_STORAGE_PGPASSWORD));
This debug-logs the password. I know there might be other places which does this, but it's not good and we should try to avoid it in the future.

2019-01-03 09:29 UTC, stackedsax commented on src/config-updater.js
> +                    value: "http://${LOCAL_IP}:5432"
Good catch, will fix.

2019-01-03 09:30 UTC, stackedsax commented on src/config-updater.js
> +                debug('Adding ' + JSON.stringify(source.PORTAL_STORAGE_PGPASSWORD));
I was merely following the conventions I saw in those other two update functions, but I'll get rid of this here.

2019-01-03 11:48 UTC, DonMartin76 commented on src/config-updater.js
> +                    value: "http://${LOCAL_IP}:5432"
Now it only writes the password, not the host. And the value for the password is a little off perhaps.

2019-01-07 08:17 UTC, DonMartin76 commented
Do you mind if I pull this in and polish the rest myself?

2019-01-07 09:23 UTC, merged