multi-route API
Haufe-Lexware/wicked.portal-env pull request #9
Opened 2019-05-02 21:59 UTC by maksimlikharev

conversion steps + test

2019-05-06 16:28 UTC, DonMartin76 requested changes

2019-05-06 16:28 UTC, DonMartin76 commented on initial-config/static/apis/petstore-oauth/config.json
> +              "/petstore"
Wrong path

2019-05-06 16:28 UTC, DonMartin76 commented on initial-config/static/apis/petstore-oauth/config.json
>          "request_path": "/petstore-oauth",
Should this stay in?

2019-05-06 16:28 UTC, DonMartin76 commented
You wrote tests for the transformation, which I like, but we don't run them during the build yet. We should think about how we can get that in as well.

2019-05-06 16:28 UTC, DonMartin76 commented
Please merge latest changes from master as well.

2019-05-07 17:44 UTC, maksimlikharev commented
different teams use different approach, but in our UI projects, normal unit tests are part of the build, and integration tests are just a separate project/repo. I can add all necessary deps/hooks into the build.

2019-11-12 22:17 UTC, closed without merging